import Sidebar from './components/sidebar/sidebar'
import MainPart from './components/mainPart/mainPart'
import './globals.css'
import { Content, Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='row'>
        <div>
          <Sidebar />
        </div>
        <div>
          <MainPart />
        </div>
        </div>

        {children}
        </body>
    </html>
  )
}
